[package]
name = "notifier"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.96"
async-trait = "0.1.86"
base64 = "0.22.1"
dotenv = "0.15.0"
fcm-rs = "0.2.0"
rdkafka = "0.37.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.139"
tokio = "1.43.0"
